services:
  mongodb:
    image: mongo:7
    container_name: blockchain-iam-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: iam_admin
      MONGO_INITDB_ROOT_PASSWORD: iam_dev_password
      MONGO_INITDB_DATABASE: blockchain_iam
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
